### ISSUE TITLE
Use BinaryBuilder.jl to package dependencies

### ISSUE THREAD

**Issue by mihalybaci** [GenericMappingTools/GMT.jl#447]
I have tried three times to install the GMT dependency for GMT.jl and so far have not been successful. On my first try, the version of GMT in  the package repos  of my OS (MX Linux/Debian) was too old (v5.4). Then I attempted to build GMT from source and ran into other issues regarding (I think) GDAL, which was also an older version (v2.3). Finally, on my new OS (Ubuntu 20.04) I have GMT version 6.0.0 and GDAL version 3.0.4, but trying to run the GMT tests gives me the following error message:

ERROR: LoadError: LoadError: could not load library "/usr/lib/x86_64-linux-gnu/libgmt.so"
/home/michael/.local/julia-1.5.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/libgdal.so.26)

Note, each time I did end up with a working version of GMT, and the only problem appears be with GMT.jl reading the dependencies. 

It would be hugely beneficial for users if GMT.jl to use BinaryBuilder.jl to ship GMT and its other dependencies with the code. This would greatly simplify the process for interested users.

**Comment by joa-quim** [comment]
I'm sorry that you have had all those troubles but unix is a complicated world and things that I don't understand keep coming up. It happens that I was able to reproduce this problem in my WSL2 that has linux 18.04 and gcc 9. Googling showed up [this ](https://stackoverflow.com/questions/52663287/glibcxx-3-4-26-not-found). So my interpretation is that the problem is that julia was built with a ``gcc`` where that bug was not yet fixed and now the conflict comes from the Julia shipped ``libstdc++.so.6``

Regarding the ``BinaryBuilder``, well the main issue is that I don't know how create generic GMT builds for unix and MacOS. And also, ``BinaryBuilder`` is very unix-centric and on Windows we use Visual Studio, not gcc. I build the GMT installer with VS, not MinGW. So, it's quite complicated to create a ``GMT_jii`` ... and these linux issues don't help.

**Comment by mihalybaci** [comment]
Thanks for the reply. I was actually able to fix the problem i posted above by compiling Julia#master from source, which used the updated version of the libraries. Unfortunately, I ran into a different issue having to do with GMT's postscriptlight.  I was considering trying to figure out the binarybuilder myself, but I've never tried it before and would probably need a working version of GMT first.

**Comment by joa-quim** [comment]
Yes, that kind of confirms the suspicion. On my side I made the experiment of just moving away the ``julia-1.5.2/bin/../lib/julia/libstdc++.so.6`` and it now complains that 
```
GMT [ERROR]: Unable to open GMT shared libgmt library: libnetcdf.so.13: cannot open shared object file: No such file or directory
```
but apparently it's a false alarm since the tests pass and I can open netcdf grids.

What is the problem with the postscript? Note that about this it might be more appropriate to post on the GMT forum.

**Comment by joa-quim** [comment]
[FYI](https://discourse.julialang.org/t/troubles-with-gcc-9/47550/2)

**Comment by joa-quim** [comment]
If you want to give it a try, the *master* version now installs GMT automatically from Conda. But the Conda version on CentOS is half broken. It needs to install an extra lib (``libnsl``) that is not shipped with ``libc`` as with other distros.

**Comment by boriskaus** [comment]
I gave this another try and managed to get a BinaryBuilder version of GMT compiling on Mac & Windows:
[https://github.com/JuliaPackaging/Yggdrasil/pull/5199](https://github.com/JuliaPackaging/Yggdrasil/pull/5199)

Yet, there are some hiccups with the windows installation. Perhaps @joa-quim or others from the GMT have some idea what needs to be changed for that to compile?

**Comment by joa-quim** [comment]
@boriskaus Thanks a lot for trying this. It's a really needed solution but unfortunately, and that's my personal view, the real problem lies on Unix that tries to force Windows be Unix and when it fails it blames Windows.

The GMT Windows build is perfectly solved with the VS build (took us several years of continuous improvements) and that is not going to be replaced by a far inferior MinGW build. But it still leaves out the *nix builds and that's where the effort should be focused. Unfortunately, even there the constrain of everything be build-able with MinGW too is severely harming the *nix side when the Win builds pose problems that have not yet been solve (e.g. GDAL, netCDF, and probably others).

I'll post this comments in the BinaryBuilder issue later today.

**Comment by boriskaus** [comment]
I'm not sure I fully follow you. 

The Linux and Mac BinaryBuilder versions already seem to compile just fine, so I guess that having that would already be very useful for `GMT.jl` (as Windows seems to work a bit better already with GMT.jl; Mac/Linux is a mess as I am repeatedly reminded about while using this in teaching). 

Or are you saying that some executables are still missing for *nix builds?

The windows version is indeed not fully compiling, but we can certainly create a `GMT_jll` without windows support. I feel that we are not missing much, though, as I can get it to compile manually (I just don't know how to link the required libs to `CMake` likely because of my limited knowledge of `CMake`

**Comment by joa-quim** [comment]
I think that for now a workable solution is to have a ``BinaryBuilder`` for unix only (Mac included). I'll have then to find a way to use it only on non-Windows platforms and use the Windows installer for Windows.
 
What I meant to say is that the unix builds will be crippled because GDAL_jll is crippled as it does include ``netCDF`` + ``HDF``. This has nothing to do with ``GMT`` nor ``CMake`` but with fact that because cross-platform build has not been able to build a GDAL with those libraries too (partially because the reason I said ``Windows-is-not-Unix``). And they are quite handy in GMT. So quite a few specialized options will not be accessible to Unix users when using the ``GMT_jll``

And, I would be delighted to know how you use GMT.jl in teaching. We could talk about nice examples that could go also to the ``being-reworked-manual``.

**Comment by joa-quim** [comment]
Hi @boriskaus 
Are you still interested in pursuing this? I think we can now make it work, but the recipe will need some changes.

**Comment by boriskaus** [comment]
Yes, I keep being interested to have this working, and I am guessing that many users of GMT.jl would also love to have a BB version.

**Comment by joa-quim** [comment]
Perfect, we should be able to do it now that GMT builds on MinGW ... despite some rocks in the way.

I guess that I must (or it's easier that way) find a way to make a tar ball available in github with the current master version that builds with MinGW.

**Comment by joa-quim** [comment]
But if you know how to fetch the source from GMT/#master that would be even better.

**Comment by boriskaus** [comment]
Yes it can be done with a bit commit; I’ll add that later

**Comment by joa-quim** [comment]
@boriskaus I think the ``GMT_jll`` is ready to test. It worked for me on WSL-Ubuntu, Centos7 and an old Mac. The default is to use the GMT_jll artifact but that can be changed to use a system wide GMT with:

- ENV["SYSTEMWIDE_GMT"] = 1;
- import Pkg; Pkg.build("GMT")
- restart Julia
 
To revert to the JLL artifact, from a clean REPL session

- import Pkg; Pkg.build("GMT")
- restart Julia

**Comment by boriskaus** [comment]
thanks! On Mac Silicon it fails with the following message:
```Julia
     Testing Running tests...
ERROR: LoadError: SystemError: opening file "/Users/kausb/.julia/dev/GMT/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:176
  [2] #systemerror#80
    @ ./error.jl:175 [inlined]
  [3] systemerror
    @ ./error.jl:175 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:275 [inlined]
  [6] open(f::Base.var"#387#388"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:382
  [7] open
    @ ./io.jl:381 [inlined]
  [8] read
    @ ./io.jl:462 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1484
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
 [11] include(x::String)
    @ GMT ~/.julia/dev/GMT/src/GMT.jl:1
 [12] top-level scope
    @ ~/.julia/dev/GMT/src/GMT.jl:43
 [13] include
    @ ./Base.jl:419 [inlined]
 [14] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [15] top-level scope
    @ stdin:1
in expression starting at /Users/kausb/.julia/dev/GMT/src/GMT.jl:1
in expression starting at stdin:1
```

**Comment by boriskaus** [comment]
Indeed, with `compile` it runs. Perhaps this is the same Heisenbug?
```Julia
[ Info: 63...
STATPLOTS: Error During Test at /Users/kausb/.julia/dev/GMT/test/test_statplots.jl:1
  Got exception outside of a @test
  Something went wrong when calling the module. GMT error number = 79
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:35
    [2] gmt(::String)
      @ GMT ~/.julia/dev/GMT/src/gmt_main.jl:311
    [3] helper_showfig4modern(show::String)
      @ GMT ~/.julia/dev/GMT/src/common_options.jl:3894
    [4] subplot(fim::Symbol; stop::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ GMT ~/.julia/dev/GMT/src/subplot.jl:128
    [5] subplot
      @ ~/.julia/dev/GMT/src/subplot.jl:45 [inlined]
    [6] cornerplot(arg1::Matrix{Float64}; first::Bool, kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:scatter,), Tuple{Bool}}})
      @ GMT ~/.julia/dev/GMT/src/statplots.jl:1291
    [7] macro expansion
      @ ~/.julia/dev/GMT/test/test_statplots.jl:90 [inlined]
    [8] macro expansion
      @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:1363 [inlined]
    [9] top-level scope
      @ ~/.julia/dev/GMT/test/test_statplots.jl:2
   [10] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [11] macro expansion
      @ ~/.julia/dev/GMT/test/runtests.jl:83 [inlined]
   [12] macro expansion
      @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:1363 [inlined]
   [13] top-level scope
      @ ~/.julia/dev/GMT/test/runtests.jl:21
   [14] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [15] top-level scope
      @ none:6
   [16] eval
      @ ./boot.jl:368 [inlined]
   [17] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:276
   [18] _start()
      @ Base ./client.jl:522
	GREENSPLINE
	MAPPROJECT
	PSMECA
	GADM
	MAKECPT
		MAKECPT - 0
		MAKECPT - 1
		MAKECPT - 2

signal (11): Segmentation fault: 11
in expression starting at /Users/kausb/.julia/dev/GMT/test/runtests.jl:5
gc_mark_loop at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
_jl_gc_collect at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_gc_collect at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_gc_pool_alloc at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
iterate at ./compiler/ssair/ir.jl:467
iterate at ./compiler/ssair/ir.jl:459 [inlined]
count_added_node! at ./compiler/ssair/ir.jl:681
setindex! at ./compiler/ssair/ir.jl:810
setindex! at ./compiler/ssair/ir.jl:818 [inlined]
ir_inline_item! at ./compiler/ssair/inlining.jl:386
```

**Comment by joa-quim** [comment]
Yes, he Heisenbug is the one that causes the ``signal (11): Segmentation fault: 11``. Several of the printings in test runs are to try to see if there is a pattern, which there is but only vaguely pointing to ``makecpt``

The other error is even more worrisome because I got it too in my ``Codespaces/Ubuntu 20.04`` but not in the other three environments where I tried (2 Linuxes and 1 MacOS/Big Sur). Now you are hitting it too. Don't know how to debug this.

**Comment by joa-quim** [comment]
The failing test is the same as if one runs this single command
```
cornerplot(randn(50,3), scatter=true)
```
I suspect that it's due to a internal (from the C lib) call to ``gs``. Can you please try installing ghostscript such that ``gs`` in the the path and then run that command above?

**Comment by joa-quim** [comment]
Bingo. Added GS to my Codespaces and now all tests pass. So now the problem is on how to solve this. We have a dependency on Ghostscript_jll but that does not the binary dir to the path so the GMT lib is not able to find it.

**Comment by boriskaus** [comment]
Ghostscript_jll does come with the binary and the path to the binary, at least on my version of it.

**Comment by joa-quim** [comment]
Yes, I know but the ``gs`` executable is not in the path so when from the GMT guts the ``gs`` executable is called, an error follows.
This is different from the situation where ``gs`` is called from a GMT wrapped module where I take care of passing in the ``gs`` full address.
```
julia> GMT.Ghostscript_jll.gs()[1]
"/home/j/.julia/artifacts/4883a6685d86b068da934537a444a6d170d71730/bin/gs"

julia> gs
ERROR: UndefVarError: `gs` not defined
```

**Comment by boriskaus** [comment]
You could do this:
```Julia
julia> gs() = run(`$(GMT.Ghostscript_jll.gs())`)
gs (generic function with 1 method)

julia> gs()
GPL Ghostscript 9.55.0 (2021-09-27)
Copyright (C) 2021 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GS>
```

I'm not really understanding how you are using `gs` with GMT. Do you pass command-line arguments, for example?

The additional information that is available in `GMT.Ghostscript_jll.gs()` is important, as it sets the path to the dynamic libraries that are required to run `gs`. In most cases, you can therefore not simply call `GMT.Ghostscript_jll.gs()[1]`.

**Comment by joa-quim** [comment]
Ghostscript is used in GMT via the ``psconvert`` module. Fortunately, many years ago, I had the idea to add an option (-G) to ``psconvert`` that lets one specify which gs executable to use. That is what is used (under the hood) when we now call the ``psconvert`` from Julia (that call is made automatically to convert the result to ``PNG`` and others). And all this works well.

**But**. In some cases the GMT binary needs also to make a call to ``gs`` for some internal reasons, and in those cases it simply expects that gs is visible through PATH and those are the cases that now fail if we don't have a, lets say, globally installed ghostscript. I tried to find a way to change the system PATH from Julia but couldn't find a way. Not even this works.
```
julia> run(`echo PATH`)
PATH
Process(`echo PATH`, ProcessExited(0))

julia> run(`echo $PATH`)
ERROR: UndefVarError: `PATH` not defined
```

**Comment by joa-quim** [comment]
I think that it would solve the case if ``run(...)`` worked, but (for me PATH is the first entry)
```
julia> run(`GMT.Ghostscript_jll.gs().env[1]`)
ERROR: LoadError: parsing command `GMT.Ghostscript_jll.gs().env[1]`: special characters "#{}()[]<>|&*?~;" must be quoted in commands

julia> run(`PATH=/home/j/.julia/artifacts/4883a6685d86b068da934537a444a6d170d71730/bin`)
ERROR: IOError: could not spawn `PATH=/home/j/.julia/artifacts/4883a6685d86b068da934537a444a6d170d71730/bin`: no such file or directory (ENOENT)
```

Packaging the ``gs`` binary is a possibility but I would leave it to a real last resort. There are other files that would need to along as well (the shared lib, fonts, etc))

**Comment by boriskaus** [comment]
yes, that is because you cannot simply run the path to the executable, as this does not set the correct environmental variables (including dynamics libraries etc.).
You can run:
```Julia
Julia> run(`$(GMT.Ghostscript_jll.gs())`)
GPL Ghostscript 9.55.0 (2021-09-27)
Copyright (C) 2021 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
```
you can also check that `GMT.Ghostscript_jll.gs()` is of type `Cmd`:
```Julia
julia> typeof(GMT.Ghostscript_jll.gs())
Cmd
```
the user guide [explains](https://docs.julialang.org/en/v1/manual/running-external-programs/#Cmd-Objects) that these are structs that contain the environmental variables. So if you run this, it will set that before executing.

There is actually a simple way to replace certain environmental variables using [addenv](https://docs.julialang.org/en/v1/base/base/#Base.addenv). We can add the path to `gs` to the `gmt` `Cmd` object in the following way:
```Julia
julia> env = GMT.GMT_jll.gmt().env;
julia> ind = findall(startswith.(env,"PATH="))[1]
julia> path_gmt = env[ind][6:end]
julia> path_gmt = env[ind][6:end]
"/Users/kausb/.julia/artifacts/b1a055a9c307b137556560efcc2cee3a6405dfd7/bin:/Users/kausb/.julia/artifacts/f987f10c94bc56fe3589d9b30a6e2f419402a31c/bin:/Users/kausb/.julia/artifacts/185bfeaa5186fb47cdc2236f5624f52e74a59cbf/bin:/Users/kausb/.julia/artifacts/9472204d25ab69d52d571b650fdc9d562455ca4a/bin:/Users/kausb/.julia/artifacts/86c32a34b06c15b5ec8d4f694c2b91435253f209/bin:/Users/kausb/.julia/artifacts/dfa09fc5bd33a68e75b575d8d6565a89814949c2/bin:/Users/kausb/.julia/artifacts/689b6368f94a3d130dce98f67b83f245bebdcbe0/bin:/Users/kausb" ⋯ 889 bytes ⋯ "Users/kausb/.julia/artifacts/1a7e22e66b523d9cb884cf85c3ec065b5fb3e5c3/bin:/Users/kausb/.julia/artifacts/bf37190b92ac2fc3dd5e7073ff7ec7bbfd10343f/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin:/Users/kausb/.julia/artifacts/57273092253ad3a7bf9733122480db4d6dc9c4b5/bin:/opt/petsc/petsc-3.16.4-opt/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/python/libexec/bin"

julia> path_gs = GMT.Ghostscript_jll.PATH_list[1]
"/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin"
julia> path_gmt_gs = path_gmt*":"* path_gs;
julia> gmt_exec = addenv(GMT.GMT_jll.gmt(), ("PATH"=> path_gmt_gs))
setenv(`/Users/kausb/.julia/artifacts/57273092253ad3a7bf9733122480db4d6dc9c4b5/bin/gmt`,["XPC_FLAGS=0x0", "COMMAND_MODE=unix2003", "PATH=/Users/kausb/.julia/artifacts/b1a055a9c307b137556560efcc2cee3a6405dfd7/bin:/Users/kausb/.julia/artifacts/f987f10c94bc56fe3589d9b30a6e2f419402a31c/bin:/Users/kausb/.julia/artifacts/185bfeaa5186fb47cdc2236f5624f52e74a59cbf/bin:/Users/kausb/.julia/artifacts/9472204d25ab69d52d571b650fdc9d562455ca4a/bin:/Users/kausb/.julia/artifacts/86c32a34b06c15b5ec8d4f694c2b91435253f209/bin:/Users/kausb/.julia/artifacts/dfa09fc5bd33a68e75b575d8d6565a89814949c2/bin:/Users/kausb/.julia/artifacts/689b6368f94a3d130dce98f67b83f245bebdcbe0/bin:/Users/kausb/.julia/artifacts/825c20e9fb9976a6dc62e1a442018fed80992c1b/bin:/Users/kausb/.julia/artifacts/3e6cbbf76c070bcec6c7db17999b509ac4b46c0d/bin:/Users/kausb/.julia/artifacts/41d2d4f312d93b56961767987cf48ea1f6d6fadc/bin:/Users/kausb/.julia/artifacts/9cd88b624c5c9ad34fec9c61621c56d465a8c717/bin:/Users/kausb/.julia/artifacts/e30df1d228e442d6b680e2ec8adf98bc9535908f/bin:/Users/kausb/.julia/artifacts/6db94dab8e98dab5bc4428a316ba3f44540bdef2/bin:/Users/kausb/.julia/artifacts/4a1a8201c8ca970558b4321430d5aae3fca6833d/bin:/Users/kausb/.julia/artifacts/df3881e810714d6a09467fe85a6fde79385fe702/bin:/Users/kausb/.julia/artifacts/e6b9fb44029423f5cd69e0cbbff25abcc4b32a8f/bin:/Users/kausb/.julia/artifacts/413111420faa4e2aeaa383c075eaa213402d939c/bin:/Users/kausb/.julia/artifacts/c325a23bc1f6521474cef5f634f18c8ab311bb02/bin:/Users/kausb/.julia/artifacts/0db9c3f6cf936a0da49e2ba954ba3e10bed6ad72/bin:/Users/kausb/.julia/artifacts/1a7e22e66b523d9cb884cf85c3ec065b5fb3e5c3/bin:/Users/kausb/.julia/artifacts/bf37190b92ac2fc3dd5e7073ff7ec7bbfd10343f/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin:/Users/kausb/.julia/artifacts/57273092253ad3a7bf9733122480db4d6dc9c4b5/bin:/opt/petsc/petsc-3.16.4-opt/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/python/libexec/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin", "PWD=/Users/kausb/.julia/dev/GMT", "DISPLAY=/private/tmp/com.apple.launchd.a3pn6YlwX0/org.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=vscode", "HOMEBREW_PREFIX=/opt/homebrew", "VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)", "SHELL=/bin/bash"  …  "FONTCONFIG_FILE=/Users/kausb/.julia/artifacts/e6b9fb44029423f5cd69e0cbbff25abcc4b32a8f/etc/fonts/fonts.conf", "INFOPATH=/opt/homebrew/share/info:", "_=/usr/local/bin/julia", "HOMEBREW_REPOSITORY=/opt/homebrew", "USER=kausb", "BASH_CONF=bash_profile", "TERM=xterm-256color", "HOME=/Users/kausb", "TERM_PROGRAM_VERSION=1.76.2", "COLORTERM=truecolor"])

```
at this stage,`gmt_exec` is a `Cmd` object that includes the path to the `gs` binary, so if you call the executable while using `run`, it should be aware of gs. I haven't tested this, though.

**Comment by joa-quim** [comment]
Thanks, very clever and I was expecting it to work but it still fails to run
```
cornerplot(randn(50,3), scatter=true)
```

I think the reason why it fails is the same that after running ``run(`gmt_exec`)``, ``run(`printenv`)`` does not show any of the ``gmt_exe`` PATH contents. Looks like those are two completely distinct PATHs.

**Comment by boriskaus** [comment]
correct, every time `run` is called it uses a new environment. Yet, you can pass the same PATH as above in the following manner:

```julia
julia> terminal_com = Cmd(`printenv`, env=("PATH"=>path_gmt_gs,));
julia> run(terminal_com);
PATH=/Users/kausb/.julia/artifacts/b1a055a9c307b137556560efcc2cee3a6405dfd7/bin:/Users/kausb/.julia/artifacts/f987f10c94bc56fe3589d9b30a6e2f419402a31c/bin:/Users/kausb/.julia/artifacts/185bfeaa5186fb47cdc2236f5624f52e74a59cbf/bin:/Users/kausb/.julia/artifacts/9472204d25ab69d52d571b650fdc9d562455ca4a/bin:/Users/kausb/.julia/artifacts/86c32a34b06c15b5ec8d4f694c2b91435253f209/bin:/Users/kausb/.julia/artifacts/dfa09fc5bd33a68e75b575d8d6565a89814949c2/bin:/Users/kausb/.julia/artifacts/689b6368f94a3d130dce98f67b83f245bebdcbe0/bin:/Users/kausb/.julia/artifacts/825c20e9fb9976a6dc62e1a442018fed80992c1b/bin:/Users/kausb/.julia/artifacts/3e6cbbf76c070bcec6c7db17999b509ac4b46c0d/bin:/Users/kausb/.julia/artifacts/41d2d4f312d93b56961767987cf48ea1f6d6fadc/bin:/Users/kausb/.julia/artifacts/9cd88b624c5c9ad34fec9c61621c56d465a8c717/bin:/Users/kausb/.julia/artifacts/e30df1d228e442d6b680e2ec8adf98bc9535908f/bin:/Users/kausb/.julia/artifacts/6db94dab8e98dab5bc4428a316ba3f44540bdef2/bin:/Users/kausb/.julia/artifacts/4a1a8201c8ca970558b4321430d5aae3fca6833d/bin:/Users/kausb/.julia/artifacts/df3881e810714d6a09467fe85a6fde79385fe702/bin:/Users/kausb/.julia/artifacts/e6b9fb44029423f5cd69e0cbbff25abcc4b32a8f/bin:/Users/kausb/.julia/artifacts/413111420faa4e2aeaa383c075eaa213402d939c/bin:/Users/kausb/.julia/artifacts/c325a23bc1f6521474cef5f634f18c8ab311bb02/bin:/Users/kausb/.julia/artifacts/0db9c3f6cf936a0da49e2ba954ba3e10bed6ad72/bin:/Users/kausb/.julia/artifacts/1a7e22e66b523d9cb884cf85c3ec065b5fb3e5c3/bin:/Users/kausb/.julia/artifacts/bf37190b92ac2fc3dd5e7073ff7ec7bbfd10343f/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin:/Users/kausb/.julia/artifacts/57273092253ad3a7bf9733122480db4d6dc9c4b5/bin:/opt/petsc/petsc-3.16.4-opt/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/homebrew/opt/python/libexec/bin:/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin
```

Along the same lines, we can verify that `gs` is available:
```julia
julia> run(Cmd(`which gs`, env=("PATH"=>path_gmt_gs,)));
/Users/kausb/.julia/artifacts/0d9e7c35bc21411c7d9c194f790e30a95a4a5795/bin/gs
```

**Comment by joa-quim** [comment]
The problem is that nothing of that make this work
```
cornerplot(randn(50,3), scatter=true)
```
I'll have to dig more in the C code to try to find a solution.

**Comment by joa-quim** [comment]
Well, I was mistaken above. Debugging shows that only the ghost executable name is stored, not it full path name.

I made some experimental changes in ``psconvert.c`` that in this branch
https://github.com/GenericMappingTools/gmt/tree/ghost-in-Julia

Could you please rebuild the GMT artifact but adding also this directive in cmake?
``/DJULIA_GHOST_JLL=True``

This goes along a change in the ``GMT_jll`` GMT.jl branch that stores the full name of the ``gs`` executable in a file at 
``~/.gmt/ghost_jll_path.txt``

A bit fragile but should hopefully work.

**Comment by boriskaus** [comment]
I think the most efficient way to move forward with this is if you compile the modified `GMT_jll` package locally (using BinaryBuilder on a *nix system), and test it locally. 
Making a PR to the GMT_jll script every time you change a bit will likely take a long time.

**Comment by joa-quim** [comment]
Yep, I'll try to see what I can lean and do with WSL.

**Comment by joa-quim** [comment]
What a painful thing this is. I build it with ``--deploy=local`` but the result is ignored. Deleting with ``] rm `` cleans nothing, it leaves all trash behind (in packages, compiled, artifacts, etc). Had to manually clean everything, to ``] dev GMT_jll`` and then it worked in a remote CentOS7. ``WSL`` was another mess and could build on it. But imported a .gz built in the CentOS, replaced the ``libgmt.so`` and it also worked, so I think all is *fine* now. Also merged the GMT branch with the modifications in master.

Changing the GitSource hash in build_tarballs.jl to
22b7b3d928993c77a505f2ca895e824b28186e97
and adding this to the ``cmake ...`` step
``-DJULIA_GHOST_JLL=True \``
should build a working version.

The only thing that still worries me a bit is that for building the docs with Franklin the CI errors apparently when creating the ``~/.gmt/ghost_jll_path.txt`` file, but nothing really works well to build the docs remotely with Franklin.

**Comment by boriskaus** [comment]
Sorry, I am very busy these days. Now that a first version of GMT_jll.jl was merged it should be straightforward to make a pull request and update that with what you write above. You do have the increment the version number, but apart from that you can just fork Yggdrasil and make a PR from your fork.

**Comment by joa-quim** [comment]
Thanks. I’ve done that yesterday. Waiting for responses

**Comment by boriskaus** [comment]
And did it solve the remaining issue?

**Comment by boriskaus** [comment]
just tried it on a Apple machine and a linux one. Both run fine for a while but end up with a segfault:
```Julia
BoundingBox: [1.0, 4.0, -0.7858315967878315, 0.27452930191489566]
Header:  -W,#0072BD
┌ Warning: The option `crop_num_lines_at_beginning` is deprecated. Use `reserved_display_lines` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The option `row_name_crayon` is deprecated. Use `row_label_crayon` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The option `nosubheader` is deprecated. Use `show_subheader` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The option `row_name_alignment` is deprecated. Use `row_label_alignment` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The option `row_name_column_title` is deprecated. Use `row_label_column_title` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: The option `row_names` is deprecated. Use `row_labels` instead.
│   caller = ip:0x0
└ @ Core :-1
[ Info: color_gradient
[ Info: line2multiseg
[ Info: mat2grid
[ Info: 2
[ Info: text_record
[ Info: test API
[ Info: test ogr2GMTdataset
[ Info: test outro1

signal (11): Segmentation fault
in expression starting at /local/home/boris/.julia/dev/GMT/test/test_misc.jl:1
gc_try_setmark at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:1764 [inlined]
gc_mark_scan_objarray at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:1876 [inlined]
gc_mark_loop at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:2267
_jl_gc_collect at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:3097
ijl_gc_collect at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:3326
maybe_collect at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:903 [inlined]
jl_gc_pool_alloc_inner at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:1247 [inlined]
jl_gc_pool_alloc_noinline at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:1306 [inlined]
jl_gc_alloc_ at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia_internal.h:369 [inlined]
jl_gc_alloc at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gc.c:3371
_new_array_ at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/array.c:134 [inlined]
_new_array at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/array.c:198 [inlined]
ijl_alloc_array_1d at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/array.c:436
Array at ./boot.jl:459 [inlined]
getindex at ./array.jl:404 [inlined]
BasicBlock at ./compiler/ssair/basicblock.jl:25 [inlined]
compute_basic_blocks at ./compiler/ssair/ir.jl:91
inflate_ir at ./compiler/ssair/legacy.jl:15
inflate_ir at ./compiler/ssair/legacy.jl:10
InliningTodo at ./compiler/ssair/inlining.jl:873 [inlined]
resolve_todo at ./compiler/ssair/inlining.jl:804
analyze_method! at ./compiler/ssair/inlining.jl:861
handle_match! at ./compiler/ssair/inlining.jl:1288
analyze_single_call! at ./compiler/ssair/inlining.jl:1205
assemble_inline_todo! at ./compiler/ssair/inlining.jl:1420
ssa_inlining_pass! at ./compiler/ssair/inlining.jl:82
jfptr_ssa_inlining_passNOT._19267.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
run_passes at ./compiler/optimize.jl:539
optimize at ./compiler/optimize.jl:504 [inlined]
_typeinf at ./compiler/typeinfer.jl:257
typeinf at ./compiler/typeinfer.jl:213
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:850
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:162
abstract_call_known at ./compiler/abstractinterpretation.jl:1696
abstract_call at ./compiler/abstractinterpretation.jl:1766
abstract_call at ./compiler/abstractinterpretation.jl:1733
abstract_eval_statement at ./compiler/abstractinterpretation.jl:1890
typeinf_local at ./compiler/abstractinterpretation.jl:2340
typeinf_nocycle at ./compiler/abstractinterpretation.jl:2462
_typeinf at ./compiler/typeinfer.jl:230
typeinf at ./compiler/typeinfer.jl:213
typeinf_ext at ./compiler/typeinfer.jl:967
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1000
typeinf_ext_toplevel at ./compiler/typeinfer.jl:996
jfptr_typeinf_ext_toplevel_18807.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia.h:1838 [inlined]
jl_type_infer at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:319
jl_generate_fptr_impl at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/jitlayers.cpp:319
jl_compile_method_internal at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2081 [inlined]
jl_compile_method_internal at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2025
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2359 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia.h:1838 [inlined]
do_call at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:467
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:522
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:522
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
include_string at ./loading.jl:1428
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
_include at ./loading.jl:1488
include at ./client.jl:476
unknown function (ip: 0x7fe54f917112)
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia.h:1838 [inlined]
do_call at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:612
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:522
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:522
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
include_string at ./loading.jl:1428
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
_include at ./loading.jl:1488
include at ./client.jl:476
unknown function (ip: 0x7fe54f917112)
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia.h:1838 [inlined]
do_call at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:126
eval_value at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:215
eval_stmt_value at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:166 [inlined]
eval_body at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:612
jl_interpret_toplevel_thunk at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/interpreter.c:750
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:906
jl_toplevel_eval_flex at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:850
ijl_toplevel_eval_in at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/toplevel.c:965
eval at ./boot.jl:368 [inlined]
exec_options at ./client.jl:276
_start at ./client.jl:522
jfptr__start_61720.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2367 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/gf.c:2549
jl_apply at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/julia.h:1838 [inlined]
true_main at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/jlapi.c:575
jl_repl_entrypoint at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/src/jlapi.c:719
main at /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/cli/loader_exe.c:59
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 908640851 (Pool: 908022365; Big: 618486); GC: 593
```
Perhaps this helps you identify where the issue occurs. 
Hardware:
```Julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 128 × AMD EPYC 7543 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 1 on 128 virtual cores
Environment:
  LD_LIBRARY_PATH = /usr/local/cuda/lib64:/opt/mpich3/lib/:/local/home/boris/Software/NLopt/install/lib
```

**Comment by joa-quim** [comment]
That's the *Heisenbug*. I only see it (but not always) when running the tests or building the docs.
I have no idea on what to do to find/fix that. Tries lots of ``@GC.preserve`` but no way.

**Comment by boriskaus** [comment]
indeed. running this again on the linux machine:
```Julia
GMTdataset[BoundingBox: [0.5578797757083167, 0.958613058526306, 0.31340903389464436, 0.9133016753726264]
2×2 GMTdataset{Float64, 2}
 Row │        X         Y 
     │  Float64   Float64 
─────┼────────────────────
   1 │ 0.958613  0.913302
   2 │ 0.55788   0.313409, BoundingBox: [0.5578797757083167, 0.958613058526306, 0.2724424231567725, 0.8791733050156636]
2×2 GMTdataset{Float64, 2}
 Row │        X         Y 
     │  Float64   Float64 
─────┼────────────────────
   1 │ 0.958613  0.272442
   2 │ 0.55788   0.879173]Extract of a GMTcpt exposed as a GMTdataset for display. Colors converted to [0-255]
Model: hsv
Color depth: 24
1×9 GMTdataset{Float64, 2}
 Row │      r1       g1       b1       r2       g2       b2    alpha       z1       z2 
     │ Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64 
─────┼─────────────────────────────────────────────────────────────────────────────────
   1 │   255.0      0.0    255.0    255.0      0.0      0.0      0.0      0.0      1.0  DRAWING
        REMOVE GARBAGE
Test Summary: | Pass  Total      Time
GMT           |  464    464  31m00.1s
     Testing GMT tests passed
```

**Comment by joa-quim** [comment]
@boriskaus could the first of [these errors](https://discourse.julialang.org/t/what-should-i-do-with-these-building-errors/97467) be due to some compat limit in the lapack dependency?

**Comment by boriskaus** [comment]
It indeed looks like that, but in the Yggdrasil build script I do not see a version specification for LAPACK, which is a bit puzzling

**Comment by joa-quim** [comment]
Yes, and that libcurl issue has been mentioned a couple of times but ignored so far. I've opened an [issue](https://github.com/JuliaLang/julia/issues/49361)

**Comment by boriskaus** [comment]
Do you need to specify a compat for libcurl or does it also compile when you leave that out?

**Comment by boriskaus** [comment]
You can just leave compat out altogether. If it is an indirect dependency that is required by some of the additional packages, there should be no need for you to even specify it.

**Comment by boriskaus** [comment]
As to GDAL_jll: you or the maintainer of GDAL would have to push an updated version to Yggdrasil that allows more recent versions of LibCURL

**Comment by joa-quim** [comment]
Not sure, GMT also needs to use libcurl directly.

This libcurl shit is transversal to many packages and the problem has been, unfortunately, more or less ignored and the level of support barely above the minimums.

**Comment by joa-quim** [comment]
In the afternoon (now I have to go to the fish market) I'll raise this question in the forum again.

**Comment by boriskaus** [comment]
If it is a dependency of `GDAL_jll` it should be downloaded automatically before compiling `GMT_jll`

As mose pointed out this appears to be unrelated to julia, but rather how libcurl is being maintained.

personally, I don’t have the slightest clue what this actually does…

**Comment by joa-quim** [comment]
It is related to Julia in the sense that on master they updated libcurl to 8.0.1 but not in the 1.9 (and previous) branches. And now we have this shit. I also don't understand why we need a libCURL_jll at all since Julia comes with that library already. And not say that libCURL_jll itself also depends **only** on 7.73

> I don’t have the slightest clue what this actually does…

It's for internet access.

**Comment by boriskaus** [comment]
LibCURL 8.0.1 is available:
https://github.com/JuliaPackaging/Yggdrasil/commit/cfca7ec5f0173d17c1c59b9e647ebfa7283b7660

**Comment by joa-quim** [comment]
PRs submitted (compat with also 8.0.1). Let's see what we get.

**Comment by boriskaus** [comment]
As long as `GDAL_jll` remains only compatible with the old version of libcurl I expect that issues remain. 
Ideally it is only a matter to create a PR with a build that is compatible with 8.0.1

**Comment by joa-quim** [comment]
Any idea on how to set a compat version range? This (in the PR) fails

![image](https://user-images.githubusercontent.com/537321/232228530-68b1a065-259b-4088-a1f1-35e26e47763f.png)

**Comment by joa-quim** [comment]
> As long as GDAL_jll remains only compatible with the old version of libcurl I expect that issues remain.

That was exactly what I thought when asked

but you saw the ( nearly incomprehensible to me, given the range of possibilities) [answer](https://github.com/JuliaLang/julia/issues/49361#issuecomment-1509720815).

**Comment by boriskaus** [comment]
Try leaving the compat argument out altogether

**Comment by joa-quim** [comment]
Had already tryed with "7.73 - 8.0.1", which seems to have passed. Let's see.

**Comment by joa-quim** [comment]
So, ``compat="7.73.0, 8.0.1"`` [worked on Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/pull/6586#event-9014438186) but not on the [jll registry](https://github.com/JuliaRegistries/General/actions/runs/4708098705)
Beautiful.

**Comment by joa-quim** [comment]
As I guessed the shit is now on GDAL side

![image](https://user-images.githubusercontent.com/537321/232325924-73d33560-cd0b-4300-a848-0a672cf5c8f2.png)

**Comment by boriskaus** [comment]
Yup, you need to push an update to `GDAL_jll` that is compiled versus the new libcurl.

**Comment by joa-quim** [comment]
GDAL is warned, now only 1656 more to go (and saying this is not a Julia problem ...)
![image](https://user-images.githubusercontent.com/537321/232330252-44f3e30c-37b5-4bff-bdd3-7e35bec79846.png)

**Comment by boriskaus** [comment]
It’s indeed a libcurl problem, who changed the main version number. Without that there would be no issues.

**Comment by joa-quim** [comment]
Merged GMT_jll branch on master. Let's see how smooth the transition will be.

**Comment by joa-quim** [comment]
GMT_jll is now the _official_ install method. Thanks again @boriskaus

**Comment by boriskaus** [comment]
great, thanks a lot!

**Comment by joa-quim** [comment]
I have colleagues in Lisbon that know you. Maybe one day I'll bug you if the long intended try of Lamem ever happens. Feel free to ask if GMT can be of more help in your group of packages.

**Comment by boriskaus** [comment]
For now we mostly use it in [GeophysicalModelGenerator](https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl) where it is already very handy to download topography datasets of a certain region. The main complaint of users was that  `GMT` would not work; with `GMT_jll` that issue should hopefully be solved.

**Comment by joa-quim** [comment]
BTW, I'm working on a better, or at least a GMT, version of [GeogRegions](https://github.com/JuliaClimate/GeoRegions.jl).
Basically all functionality is already there, but a friendlier interface won't hurt.

**Comment by boriskaus** [comment]
hmm, in fact adding GMT as a dependency causes all kinds of compatibility issues, as can be seen [here](https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/actions/runs/5113745788/jobs/9193295054).
Not sure what the best way is to solve that..

**Comment by joa-quim** [comment]
Yes, we know that (remember https://github.com/GenericMappingTools/GMT.jl/issues/447#issuecomment-1510423388).
I've opened issues in GDAL and GEOS warning about the _libCURLpocalypse_ but nothing has happened yet.
You can only use nightly on Windows, otherwise 1.9 works fine.

**Comment by joa-quim** [comment]
So it's not finding ``/workspace/destdir/share/matlab/jet.cpt`` but how comes it is looking for ``jet.cpt`` in that directory. Its location is

``.julia\artifacts\49ddd67a39d3e0f2c7e309821ec74e592b3c8dda\share\cpt\matlab``

does this also fail? 
```makecpt(:jet)```

Any way to reproduce this?

**Comment by boriskaus** [comment]
I can't reproduce this locally, only under the CI pipeline which makes debugging rather difficult

**Comment by joa-quim** [comment]
That's what I feared. GMT looks for an environment variable called ``GMT6_SHAREDIR`` or ``GMT_SHAREDIR``  to point to other than the default share dir. Is it possible that something in that action sets this env var.
Can you add a ``printenv | grep GMT6_SH`` in the action to see if something pops up?
